### ISSUE TITLE
Support glslify in string literals

### ISSUE THREAD

**Issue by hsimpson** [hsimpson/vscode-glsllint#18]
String literals in at least JS, JSX, TS, TSX, glslify should be supported

**Comment by zakjan** [comment]
This is great! How complex would it be to add support also to standalone files?

**Comment by hsimpson** [comment]
What do you mean by standalone files? Could you describe it a bit more?

**Comment by zakjan** [comment]
`*.frag`, `*.vert` files with glslify import syntax, referencing other `*.glsl` files

Such files can be imported into the application with bundler plugins https://github.com/glslify/glslify-loader, https://github.com/glslify/rollup-plugin-glslify etc.

**Comment by hsimpson** [comment]
This should already be supported see #4 
If there is any problem, please create a new issue with error description and probably example shader files so I can investigate the problem.

**Comment by zakjan** [comment]
All right, it seems to work, or I might have a different issue, thanks!
