### ISSUE TITLE
Allow configuring glslify options via extension settings

### ISSUE THREAD

**Issue by bduffany** [hsimpson/vscode-glsllint#19]
It would be nice to be able to provide a custom `options` object to `glslify`, specifically for overriding `basedir`. Or add some documentation to the README that `basedir` is currently hard-coded to the workspace root path.

**Comment by jsonkao** [comment]
This would be very helpful :)

**Comment by hsimpson** [comment]
> 
> 
> The custom option would be very helpful :) Or maybe a different path resolution algorithm?
> 
> Thanks so much for your work on this extension.

I will look in the options of glslify.

**Comment by hsimpson** [comment]
Will be available in the next release

**Comment by jsonkao** [comment]
Thank you <3

**Comment by bduffany** [comment]
Awesome! Thanks!
