### ISSUE TITLE
Allow disabling auto-open of (glslified) file on error

### ISSUE THREAD

**Issue by bduffany** [hsimpson/vscode-glsllint#20]
When there is an error, VSCode auto-opens the `*-(glslified)` compiled source, which is inconvenient because it always seems to open in the same editor window of the file that I'm currently editing. Sometimes I am pasting code from an external example which will contain errors and don't necessarily want to fix all the errors before the first save. I would love an option to disable the glslified auto-open functionality so that the glslified file doesn't keep popping over my active editor while I am slowly fixing & saving some code that I've pasted. I would rather not disable the linter altogether, because ideally I would like to be able to see errors as I am fixing but not necessarily have the glslified version continually interrupting as I save.

**Comment by hsimpson** [comment]
This would be easy to implement.

**Comment by hsimpson** [comment]
This will be available in the next release

**Comment by bduffany** [comment]
Amazing! Thank you
