### ISSUE TITLE
Error compiling glslify file with relative module imports

### ISSUE THREAD

**Issue by franjaviersans** [hsimpson/vscode-glsllint#35]
I have a relative import in my files like this:

`#pragma glslify: someModule = require("../../shaders/utils/someModule.glsl")`

And the extension fails to compile like this:

`GLSL Lint: GLSL Lint: failed to compile the glslify file! Error: Cannot find module`

As it is using only the `basedir` indicated as an option or the working directory path.

Is it possible to set an option to solve the import relative to the current file directory?

**Comment by hsimpson** [comment]
Should not be a complex thing to implement, I will check this.

**Comment by hsimpson** [comment]
> @hsimpson yes, it does work perfectly. Thank you!

Nice, then I will officially release this version.

**Comment by hsimpson** [comment]
@franjaviersans oh thanks for closing 👍 
I have forgot this.
