### ISSUE TITLE
Stop extension from writing spir-v files on save

### ISSUE THREAD

**Issue by Benedikt-beeclever** [hsimpson/vscode-glsllint#38]
Hey, 
is there any way to stop the extension from generating spir-v files inside my workdirectory? If not is there any way to set the output path so the compiled shader files get written to another directory instead of the root of my workdirectory? 

Thanks in advance.

**Comment by hsimpson** [comment]
Could you show me your config (at least the part with `glsllint`)
Which OS, and which version of glslangValidator are you using (`glslangValidator --version`)

Could you also show a minimal part of your shader(s).

I think of adding a configuration to control the SPIR-V output or delete them after linting.

**Comment by Benebaby** [comment]
Vertex Shader:
`#version 450

layout(binding = 0) uniform UniformBufferObject {
    mat4 model;
    mat4 view;
    mat4 proj;
    vec2 size;
} ubo;

layout(location = 0) in vec3 inPosition;
layout(location = 1) in vec3 inColor;
layout(location = 2) in vec3 inNormal;
layout(location = 3) in vec2 inTexCoord;

layout(location = 0) out vec3 fragColor;
layout(location = 1) out vec2 fragTexCoord;
layout(location = 2) out mat4 invModel;
layout(location = 6) out mat4 invView;
layout(location = 10) out mat4 invProj;
layout(location = 14) out vec2 size;


void main() {
    gl_Position = ubo.proj * ubo.view * ubo.model * vec4(inPosition, 1.0);
    fragColor = inColor;
    fragTexCoord = inTexCoord;
    invModel = inverse(ubo.model);
    invView = inverse(ubo.view);
    invProj = inverse(ubo.proj);
    size = ubo.size;
}`

Fragment Shader: 
`#version 450

struct Ray {
	vec3 origin;
	vec3 direction;
};


struct AABBox { 
    vec3 bounds[2];
};

layout(binding = 1) uniform sampler2D texSampler;

layout(origin_upper_left) in vec4 gl_FragCoord;
layout(location = 0) in vec3 fragColor;
layout(location = 1) in vec2 fragTexCoord;
layout(location = 2) in mat4 invModel;
layout(location = 6) in mat4 invView;
layout(location = 10) in mat4 invProj;
layout(location = 14) in vec2 size;

layout(location = 0) out vec4 outColor;

Ray calculateRay(vec2 offset) {
    vec2 pixelCenter = vec2(gl_FragCoord.xy) + offset;
	vec2 inUV = pixelCenter / size;
	vec2 d = inUV * 2.0 - 1.0;
	vec4 target = invProj * vec4(d.x, d.y, 1, 1) ;
    Ray ray;
    ray.origin = vec4(invModel * invView * vec4(0,0,0,1)).xyz;
    ray.direction = vec4(invModel * invView * vec4(normalize(target.xyz), 0)).xyz;
    return ray;
}

bool intersect(in Ray r, in AABBox box, out float tmin, out float tmax) { 
    float tymin, tymax, tzmin, tzmax, t; 
    vec3 invDir = (1.0 / r.direction);
    if(invDir.x < 0){
        tmin = (box.bounds[1].x - r.origin.x) * invDir.x;
        tmax = (box.bounds[0].x - r.origin.x) * invDir.x; 
    }else{
        tmin = (box.bounds[0].x - r.origin.x) * invDir.x;
        tmax = (box.bounds[1].x - r.origin.x) * invDir.x; 
    }
    if(invDir.y < 0){
        tymin = (box.bounds[1].y - r.origin.y) * invDir.y; 
        tymax = (box.bounds[0].y - r.origin.y) * invDir.y; 
    }else{
        tymin = (box.bounds[0].y - r.origin.y) * invDir.y; 
        tymax = (box.bounds[1].y - r.origin.y) * invDir.y;
    }
    if ((tmin > tymax) || (tymin > tmax)) 
        return false; 
    if (tymin > tmin) 
        tmin = tymin; 
    if (tymax < tmax) 
        tmax = tymax; 
    if(invDir.z < 0){
        tzmin = (box.bounds[1].z - r.origin.z) * invDir.z; 
        tzmax = (box.bounds[0].z - r.origin.z) * invDir.z; 
    }else{
        tzmin = (box.bounds[0].z - r.origin.z) * invDir.z; 
        tzmax = (box.bounds[1].z - r.origin.z) * invDir.z;
    }
    if ((tmin > tzmax) || (tzmin > tmax)) 
        return false; 
    if (tzmin > tmin) 
        tmin = tzmin; 
    if (tzmax < tmax) 
        tmax = tzmax; 
    t = tmin; 
    if (t < 0) { 
        t = tmax; 
        if (t < 0) 
            return false; 
    } 
    return true; 
} 

void main() {
    vec3 color = vec3(0.0);
    Ray ray = calculateRay(vec2(0.0));
    AABBox box; 
    box.bounds[0] = vec3(-0.5); 
    box.bounds[1] = vec3(0.5);
    float tmin = 0.0;
    float tmax = 0.0;
    bool intersects = intersect(ray, box, tmin, tmax);
    vec3 enter = ray.origin + tmin * ray.direction;
    vec3 exit = ray.origin + tmax * ray.direction;

    //highlight frontfacing edges
    if((enter.x < -0.497 || enter.x > 0.497) && (enter.z < -0.497 || enter.z > 0.497)){
        float distanceToEdge = ((0.5 - abs(enter.x)) + (0.5 - abs(enter.z))) / 2.0;
        color += (1.0 - distanceToEdge * 333.333) * vec3(0.0, 1.0, 0.0) * 0.4;
    }
    if((enter.y < -0.497 || enter.y > 0.497) && (enter.x < -0.497 || enter.x > 0.497)){
        float distanceToEdge = ((0.5 - abs(enter.y)) + (0.5 - abs(enter.x))) / 2.0;
        color += (1.0 - distanceToEdge * 333.333) * vec3(0.0, 1.0, 0.0) * 0.4;
    }
    if((enter.z < -0.497 || enter.z > 0.497) && (enter.y < -0.497 || enter.y > 0.497)){
        float distanceToEdge = ((0.5 - abs(enter.z)) + (0.5 - abs(enter.y))) / 2.0;
        color += (1.0 - distanceToEdge * 333.333) * vec3(0.0, 1.0, 0.0) * 0.4;
    }

    if(intersects){
        vec3 currentColor = vec3(0.0);
        for(float t = tmin; t < tmax ; t += 0.003906){
            vec2 uv = (ray.origin + t * ray.direction).xy + vec2(0.5);
            vec3 textureColor = texture(texSampler, uv).rgb;
            if(length(textureColor) < 0.05)
                currentColor += vec3(0.0, 0.05, 0.05) * 0.003906;
            else
                currentColor += textureColor * vec3(1.0, 1.0, 1.0) * 0.007812;
        }
        color += currentColor;
    }else{
        color += vec3(0.0);
    }

    //highlight backfacing edges
    if((exit.x < -0.497 || exit.x > 0.497) && (exit.z < -0.497 || exit.z > 0.497)){
        float distanceToEdge = ((0.5 - abs(exit.x)) + (0.5 - abs(exit.z))) / 2.0;
        color += (1.0 - distanceToEdge * 333.333) * vec3(0.0, 1.0, 0.0) * 0.1;
    }
    if((exit.y < -0.497 || exit.y > 0.497) && (exit.x < -0.497 || exit.x > 0.497)){
        float distanceToEdge = ((0.5 - abs(exit.y)) + (0.5 - abs(exit.x))) / 2.0;
        color += (1.0 - distanceToEdge * 333.333) * vec3(0.0, 1.0, 0.0) * 0.1;
    }
    if((exit.z < -0.497 || exit.z > 0.497) && (exit.y < -0.497 || exit.y > 0.497)){
        float distanceToEdge = ((0.5 - abs(exit.z)) + (0.5 - abs(exit.y))) / 2.0;
        color += (1.0 - distanceToEdge * 333.333) * vec3(0.0, 1.0, 0.0) * 0.1;
    }

    outColor = vec4(color, 1.0);
}`

Glsllint config:

`{
    "workbench.colorTheme": "Default Dark+",
    "git.autofetch": true,
    "files.autoSave": "onFocusChange",
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "[json]": {
        "editor.defaultFormatter": "HookyQR.beautify"
    },
    "[html]": {
        "editor.defaultFormatter": "vscode.html-language-features"
    },
    "cmake.configureOnOpen": true,
    "explorer.confirmDelete": false,
    "glsllint.glslangValidatorArgs": "--target-env vulkan1.1",
    "glsllint.glslifyUseCurrentFileAsBasedir": true
}`

Glslang Version: 10:11.6.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 11.6.0
GLSL Version: 4.60 glslang Khronos. 11.6.0
SPIR-V Version 0x00010500, Revision 4
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 10
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
------------------------------

An option to control the Spir-V Output would be awesome.

Thanks

**Comment by hsimpson** [comment]
Ok I can reproduce this problem. 
There is no option in glslangValidator to avoid writing the output file.

What do you think about just writing the output file of `glslangValidator` to $TEMP and remove it after validation.

**Comment by Benebaby** [comment]
This is one possible case and should be default. Another good option would be to give the extension an output path setting if someone wants to expcitly write the output to a directory.

**Comment by hsimpson** [comment]
I prefer the $TEMP way without another config option, as a default behaviour. The user should not relay on the written spir-v binary.

If the user needs a spir-v binary than the user can create it by using glslangValidator or glslc (probably from vulkan SDK) to build it.
