### ISSUE TITLE
threejs base vertex shader global variables not working

### ISSUE THREAD

**Issue by snake89322** [hsimpson/vscode-glsllint#39]
```Base.vert
void main(void) {
  gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.);
}
```

glsl lint error:
'projectionMatrix' : undeclared identifier 
'' : compilation terminated 

how to disable the lint or declare global variable.

**Comment by hsimpson** [comment]
Duplicate of #27

**Comment by jkiss** [comment]
just uninstall this plugin 🥲
