### ISSUE TITLE
Most recent PR for issue #38 introduces a bug for default settings.

### ISSUE THREAD

**Issue by lou000** [hsimpson/vscode-glsllint#42]
With default settings im getting an error:

`GLSL Lint: Wrong parameters when starting glslangValidator. Arguments: -l --stdin -S comp -o C:\Users\Admin\AppData\Local\Temp\vscode-glsllint-comp.tmp -Ic:\Users\Admin\Documents\GitHub\Primor_Engine\assets\shaders stderr: glslangValidator.exe: Error: no binary generation requested (e.g., -V) (use -h for usage) `

This happens because glslangValidator requires that running with option "-o" has to generate a binary,
`-o <file>   save binary to <file>, requires a binary option (e.g., -V)`
 it does when this setting is present:
`"glsllint.glslangValidatorArgs": "--target-env vulkan1.1"` 
I think thats because it has to generate binary for SPIRV
With default settings it throws above error.

**Comment by hsimpson** [comment]
Damn, thanks for addressing this.

**Comment by hsimpson** [comment]
@lou000 I have created a bugfix which is in 1.7.1 Release: https://github.com/hsimpson/vscode-glsllint/releases/tag/1.7.1
You can try to use this vsix, and confirm if it is working. I will release this version ASAP.

**Comment by hsimpson** [comment]
> @hsimpson Yep works like a charm. Thanks a lot!

Nice, then I will publish the 1.7.1
