### ISSUE TITLE
GLSL Lint: Failed to spawn 'glslangValidator' binary

### ISSUE THREAD

**Issue by TheBricktop** [hsimpson/vscode-glsllint#46]
I know that there is another same error thread but it didn't answered my problem exactly.
ive put the prebuilt binaries from https://github.com/KhronosGroup/glslang to the C:\bin\
![obraz](https://user-images.githubusercontent.com/3866030/151358878-f96def30-2674-4d07-bccb-f6879ac296aa.png)
then ive typed the glslangValidator.exe path to the glslint path 
![obraz](https://user-images.githubusercontent.com/3866030/151359000-d5422ded-5701-4d98-bfd1-1eff226eff64.png)
like that
and got the enoent error 
so ive experimented with path like C:\bin , C:\\bin\\, C:/bin/, C:\bin\glslangValidator.exe, and stuff 
but every time im getting the enoent error,
what is the proper way of setting this up cause im out of ideas.

**Comment by hsimpson** [comment]
In the `settings.json` file it should be: `C:\\bin\\glslangValidator.exe` which renders in the VSCode settings UI as `C:\bin\glslangValidator.exe`
Additional hints for `settings.json`: https://code.visualstudio.com/docs/getstarted/settings

**Comment by TheBricktop** [comment]
![obraz](https://user-images.githubusercontent.com/3866030/151365199-82ca6632-c544-458c-b032-d3fc687b9579.png)

that gave me
![obraz](https://user-images.githubusercontent.com/3866030/151365266-c5d8147a-d38c-4e6c-8941-5c4a60950dca.png)

**Comment by hsimpson** [comment]
This is weird ;-)
Could you open and command window and type: `C:\bin\glslangValidator.exe --help` and look what the output is?
Otherwise I will try to debug this on Windows next week.
Which VSCode version are you using and which Extension version are using?

**Comment by hsimpson** [comment]
Nice, so probably some hickup.
About the `pow()`function could you attach a minimal shader example?

**Comment by TheBricktop** [comment]
is gl_ModelViewProjectionMatrix non generic?
![obraz](https://user-images.githubusercontent.com/3866030/151535551-90d5a7b6-5b55-4fb4-8637-047be44efcd9.png)


`
#version 150
//precision mediump float;
//panda3d
varying vec2 texcoord0; 

void main()
{
  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
  texcoord0 = vec2(gl_MultiTexCoord0[0], gl_MultiTexCoord0[1]);
}

`

**Comment by hsimpson** [comment]
Sorry for late answer, but I'm very busy these days 🤣
`gl_ModelViewProjectionMatrix`is only available in the compatibility profile, so you have to add it to the version derictive, your complete shader would look like:
```glsl
#version 150 compatibility
//precision mediump float;
//panda3d
varying vec2 texcoord0;

void main()
{
    gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;
    texcoord0 = vec2(gl_MultiTexCoord0[0], gl_MultiTexCoord0[1]);
}
```

Then it will lint without any error
