### ISSUE TITLE
Ignores glslangValidatorPath

### ISSUE THREAD

**Issue by szabotudor** [hsimpson/vscode-glsllint#47]
Setting the path for the glslangValidator does nothing, and only works when glslangValidator is put right next to the file.

**Comment by hsimpson** [comment]
`glslangValidatorPath` means the complete path to the executable inclusive the executable itself.

**Comment by szabotudor** [comment]
The problem was not that, but still it was from my end, which is why I closed the issue. Sorry for the inconvenience.
