### ISSUE TITLE
'gl_VertexIndex' : undeclared identifier 

### ISSUE THREAD

**Issue by dortamiguel** [hsimpson/vscode-glsllint#51]
I'm writting some glsl for a vulkan shader and when I try to use the global variable gl_VertexIndex y get the error `'gl_VertexIndex' : undeclared identifier` though it works fine whe I compile and use the shader.

The is something I should do to config the extension to know that this variable is available?

**Comment by hsimpson** [comment]
For vulkan shaders you need an additional flag for the glslangValidator, please use `"glsllint.glslangValidatorArgs": "-V",` see: https://github.com/hsimpson/vscode-glsllint#extension-settings

**Comment by ellipticaldoor** [comment]
@hsimpson thank you! that worked
