### ISSUE TITLE
Publish to OpenVSX

### ISSUE THREAD

**Issue by filiptronicek** [hsimpson/vscode-glsllint#54]
Hi there @hsimpson 👋!
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [OpenVSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is OpenVSX? Why does it exist?

OpenVSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/) based IDEs, and so on.

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the command `ovsx publish` to publish your plugin. See this example from RedHat publishes their Java extension: [redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82](https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82)
You can also find [an example PR](https://github.com/PeterWone/vsc-print/pull/121) that contributes a release GitHub Action which publishes to GitHub, MS and OpenVSX at the same time.

I saw that the extension is not published via the GitHub Action to the Microsoft Marketplace, but I think it could be something worth considering, since to publish to OpenVSX and the MS Marketplace could be really easily automated and made nice. I'd love to help with that or any questions about OpenVSX if they occur.

**Comment by hsimpson** [comment]
What a bad accounting experience...

**Comment by hsimpson** [comment]
And why is there no possibility to upload an extension for publishing, via the website?

**Comment by filiptronicek** [comment]
@hsimpson sorry to hear you having issues. Uploading via the website will be something that will be available soon, [the PR for it](https://github.com/eclipse/openvsx/pull/437) is ready to be merged.

**Comment by hsimpson** [comment]
Ok I tried to publish the extension, but it is not possible, because of a dependency:
`❌  Cannot resolve dependency: slevesque.shader`

So this can only work when the extension is no longer depending on the other one.

**Comment by hsimpson** [comment]
#25

**Comment by filiptronicek** [comment]
Hey again @hsimpson, I have published [`slevesque.shader`](https://open-vsx.org/extension/slevesque/shader) to https://open-vsx.org, could you try again? 🙏

**Comment by hsimpson** [comment]
Extension is now published: https://open-vsx.org/extension/dtoplak/vscode-glsllint

**Comment by metaleap** [comment]
@filiptronicek / @GitMensch / @hsimpson just in case you have insights into this — as a user of the fine fork named @VSCodium, I'm glad you guys went through this exercise once, well over a year ago.

But it begs the question, does OpenVSX not offer some Github-integrated _"package update flow"_ (actions? webhooks? dunno) as well? Because now the OpenVSX one is of course about a year out of date compared to the latest Github-linked release   =)

**Comment by GitMensch** [comment]
Agreed. @hsimpson please send newer versions to Open VSX, too.

Note: You could also use a [GitHub action](https://docs.github.com/en/actions) that allows publishing to both Open VSX and the MS market place, [HaaLeo/publish-vscode-extension](https://github.com/HaaLeo/publish-vscode-extension#readme) does this.

**Comment by hsimpson** [comment]
Version 1.8.1 (current) is published to OpenVSX
