### ISSUE TITLE
Shows error when using GL_EXT_ray_tracing, code works fine.

### ISSUE THREAD

**Issue by ThomasConrad** [hsimpson/vscode-glsllint#60]
Hi, I am new to glsllint. I am running the NVPRO KHR ray tracing samples, and when loading the GL_EXT_ray_tracing extension i get a linting error that it's not supported for the targeted spir-V version. I believe this might be due to glslc running with the default vulkan=1.0 instead of the newer 1.2, but I do not know how to change this. Here is the concrete shader I am having issues with: [https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/master/ray_tracing__simple/shaders/raytrace.rmiss](https://github.com/nvpro-samples/vk_raytracing_tutorial_KHR/blob/master/ray_tracing__simple/shaders/raytrace.rmiss).

**Comment by hsimpson** [comment]
I will check this...

**Comment by hsimpson** [comment]
If you configure `"glsllint.glslangValidatorArgs": "--target-env vulkan1.2"` then it will lint the VK Raytracing shaders correctly.
If you running `glslangValidator --help` it will show you all options
