### ISSUE TITLE
GLSL Lint: Failed to spawn 'glslangValidator' binary on MacOS 13.3

### ISSUE THREAD

**Issue by keman5** [hsimpson/vscode-glsllint#64]
I got this errors:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/116868115/236093775-96d8dfcb-f7f5-4f16-bf01-14a7bb595d48.png">
Glslang Version: 11:12.1.0
<img width="357" alt="image" src="https://user-images.githubusercontent.com/116868115/236094499-66915014-3866-4186-ba88-78d7b1d73757.png">
on MacOS13
<img width="496" alt="image" src="https://user-images.githubusercontent.com/116868115/236094725-b91ca505-4548-4189-bbc8-4f58e5a4c21b.png">
My configuration:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/116868115/236095050-7a20622d-c3e3-4e76-957e-a4c2f3428bc0.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/116868115/236095137-148152d3-da7d-472d-ac5d-f2eecaef8c6d.png">

I'm a new to openGL/shaders, please help me out, thanks

**Comment by hsimpson** [comment]
You have to configure the `glsllint.glslangValidatorPath` to the executable it self. In your case: `/Users/admin/glslang-validator/bin/glslangValidator` then it should work.

**Comment by keman5** [comment]
Thanks, it works fine.
