### ISSUE TITLE
【Help】GLSL Lint: Failed to spawn 'glslangValidator' binary. 

### ISSUE THREAD

**Issue by IWSR** [hsimpson/vscode-glsllint#71]
My device: Windows 11 & WSL

Version of GLSL Lint: v1.8.1

Greetings! I've run into a few issues about glsllint. VSCode gave me the error as shown in the title.

![image](https://github.com/hsimpson/vscode-glsllint/assets/18499412/b295eb8c-ad0f-4adc-b2f1-ad9b8661c977)

But I'm sure I placed the validator in $PATH. The reason is that I can access it in the terminal.

![image](https://github.com/hsimpson/vscode-glsllint/assets/18499412/7216da34-7b1e-4ed0-a685-9acb6f2f3070)

I tried specifying the corresponding path in glslangValidatorPath, but I couldn't find the corresponding fill-in location in vscode settings. Even specifying glsllint.glslangValidatorPath in the JSON didn't work.

![image](https://github.com/hsimpson/vscode-glsllint/assets/18499412/6e5af555-307c-4ff4-91ca-073002e63b18)

The thing is, there is simply no place to fill in the path here.

Looking forward to your assistance, thank you very much.

**Comment by hsimpson** [comment]
It should work if it is in your PATH. Probably restart your VSCode to respect the PATH env..
It is strange that the `Glslang Validator Path` Setting is missing on your side.
It should look like this (the "Not synced" depends on your sync settings)
![image](https://github.com/hsimpson/vscode-glsllint/assets/3650693/1313e146-ff07-4b19-a6b3-0dccbbec3f27)

Could you post the extension version and the vscode version.

**Comment by IWSR** [comment]
> It should work if it is in your PATH. Probably restart your VSCode to respect the PATH env..如果它在您的路径中，它应该可以工作。可能需要重新启动 VSCode 以尊重 PATH 环境.. It is strange that the `Glslang Validator Path` Setting is missing on your side. 奇怪的是，您这边缺少 `Glslang Validator Path` 设置。 It should look like this (the "Not synced" depends on your sync settings) 它应该看起来像这样（“未同步”取决于您的同步设置） ![image](https://private-user-images.githubusercontent.com/3650693/287653537-1313e146-ff07-4b19-a6b3-0dccbbec3f27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODY5NTEsIm5iZiI6MTcwMTY4NjY1MSwicGF0aCI6Ii8zNjUwNjkzLzI4NzY1MzUzNy0xMzEzZTE0Ni1mZjA3LTRiMTktYTZiMy0wZGNjYmJlYzNmMjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTA0NDExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM5OGZiNzdlMmNhNWM2OTE2YWM4NDQ4MTA4NzA0OGQ4MDgzYjkzZWE3ZDUxNTQ5ZGEyNzY1NTMwMGFjYjNmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MO48oeE7Ntx7gqbSJCyPHt5TYdIewhyTn9d3b6428uc)
> 
> Could you post the extension version and the vscode version.你能发布扩展版本和 vscode 版本吗？

Thank you for your reply. The version of GLSL Lint is v1.8.1 and the version of vscode is 1.84.2

![image](https://github.com/hsimpson/vscode-glsllint/assets/18499412/9136e5f0-245e-4777-b0d2-a7c72d7b3227)

**Comment by IWSR** [comment]
Restart vscode is not work for me.

**Comment by IWSR** [comment]
@hsimpson Thank you very much for your help. I resolved the issue. My development environment is within WSL, but I had only installed glslangValidator on Windows. VSCode, when used for WSL development, relies on environment variables within WSL. The problem was resolved after I installed glslangValidator within WSL. Thanks again, my friend.

**Comment by hsimpson** [comment]
> @hsimpson Thank you very much for your help. I resolved the issue. My development environment is within WSL, but I had only installed glslangValidator on Windows. VSCode, when used for WSL development, relies on environment variables within WSL. The problem was resolved after I installed glslangValidator within WSL. Thanks again, my friend.

Fine. Glad it worked now on your site.
